server:
  port: 5454


netty-ws:
  port: 5455
  max-content-length: 4096
  max-frame-size: 65536
  reader-idle-sec: 5
  reader-idle-cnt: 2

spring:
  redis:
    cluster:
      nodes:
        - 192.168.16.203:6589
        - 192.168.16.204:6589
        - 192.168.16.205:6589
      max-redirects: 5
    # 密码
    password: 'jszt20.v'
    #    password: ''
    # 连接超时时间
    timeout: 10s
    database: 0
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms